"""Read PENELOPE's elastic data out of a .mat file generated by PenRed.

Diagnostic only. The point is to separate a data problem from an implementation
problem by feeding OpenMC's own transport different elastic numbers and
changing nothing else -- see README.md.

The .mat carries, for electrons:

  *** Electron and positron elastic cross sections, NDATA = 111
      one row per energy: E, CS, CS1, CS2 (electron) then the same for positrons
  *** Electron elastic differential cross sections
      one block per energy: a header "-1 E CS CS1 CS2" then NA=606 DCS values

The angular grid is not stored -- it is built by the code, in degrees, with the
step refined near zero. This reproduces it exactly (pen_material.cpp, "Angular
grid (TH in deg, XMU=(1-cos(TH))/2)").
"""
import numpy as np

NA = 606

def angular_grid():
    """PENELOPE's 606-point grid, returned as theta in degrees and mu=cos(theta)."""
    th = np.empty(NA)
    th[0] = 0.0
    th[1] = 1.0e-4
    for i in range(2, NA):
        p = th[i-1]
        if p < 0.9999e-3:   st = 2.5e-5
        elif p < 0.9999e-2: st = 2.5e-4
        elif p < 0.9999e-1: st = 2.5e-3
        elif p < 0.9999:    st = 2.5e-2
        elif p < 0.9999e1:  st = 1.0e-1
        elif p < 2.4999e1:  st = 2.5e-1
        else:               st = 5.0e-1
        th[i] = p + st
    return th, np.cos(np.radians(th))

def read_mat(path):
    """(E, CS, CS1, CS2) on PENELOPE's 111-point grid, and DCS[111, 606].

    Energies in eV, cross sections in cm^2, DCS in cm^2/sr.
    """
    lines = open(path).read().splitlines()
    i = next(k for k, l in enumerate(lines) if "elastic cross sections" in l)
    n = int(lines[i].split("=")[-1])
    tab = np.array([[float(x) for x in lines[i+1+j].split()] for j in range(n)])

    # The DCS is tabulated on fewer energies than the integrated cross
    # sections -- 96 against 111 for carbon -- so read what is there and match
    # each block back to its row by energy rather than assuming they align.
    j = next(k for k, l in enumerate(lines) if "Electron elastic differential" in l)
    stop = next((k for k, l in enumerate(lines[j+1:], j+1)
                 if "Positron elastic differential" in l), len(lines))
    rows, E = [], []
    k = j + 1
    while k < stop:
        parts = lines[k].split()
        if not parts or parts[0] != "-1":
            k += 1; continue
        E.append(float(parts[1])); k += 1
        buf = []
        while len(buf) < NA and k < stop:
            buf += [float(x) for x in lines[k].split()]; k += 1
        rows.append(buf[:NA])
    E = np.array(E); dcs = np.array(rows)
    idx = np.searchsorted(tab[:, 0], E)
    if not np.allclose(tab[idx, 0], E, rtol=1e-9):
        raise ValueError("a DCS energy is absent from the cross-section table")
    return E, tab[idx, 1], tab[idx, 2], tab[idx, 3], dcs

def moments(mu, dcs):
    """sigma, sigma_tr1 by integrating the DCS over solid angle.

    mu descends from 1 to -1, so integrate against -dmu and 2*pi.
    """
    s0 = 2*np.pi*np.trapezoid(dcs[::-1], mu[::-1])
    s1 = 2*np.pi*np.trapezoid((dcs*(1.0-mu))[::-1], mu[::-1])
    return s0, s1

if __name__ == "__main__":
    import sys
    E, CS, CS1, CS2, DCS = read_mat(sys.argv[1])
    th, mu = angular_grid()
    print(f"{len(E)} energies, {DCS.shape[1]} angles, "
          f"{E[0]:.4g} to {E[-1]:.4g} eV")
    print(f"{'E (eV)':>11s} {'sigma int':>11s} {'sigma tab':>11s} {'ratio':>7s} "
          f"{'tr1 int':>11s} {'tr1 tab':>11s} {'ratio':>7s}")
    for k in range(0, len(E), 15):
        s0, s1 = moments(mu, DCS[k])
        print(f"{E[k]:11.4e} {s0:11.4e} {CS[k]:11.4e} {s0/CS[k]:7.4f} "
              f"{s1:11.4e} {CS1[k]:11.4e} {s1/CS1[k]:7.4f}")
