#include <cmath>
#include <iostream>
#include <string>

#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_floating_point.hpp>

#include "openmc/charged_particle.h"
#include "openmc/hdf5_interface.h"

using namespace openmc;

TEST_CASE("Test Charged Particle Data Loading")
{
  // Path to test data file (generated by Python with new format)
  std::string filename = "data/deuteron_H2_new.h5";

  // Read charged particle data
  read_charged_particle_data(filename);

  REQUIRE(data::charged_particles.size() == 1);

  auto& cp = *data::charged_particles[0];

  SECTION("Verify attributes")
  {
    CHECK(cp.projectile_ == "deuteron");
    CHECK(cp.target_ == "H2");
    CHECK(cp.name_ == "deuteron_H2");
    CHECK(cp.Z_ == 1);
    CHECK(cp.A_ == 2);
    CHECK(cp.metastable_ == 0);
    // ENDF-B-VIII.1 value
    CHECK_THAT(cp.awr_, Catch::Matchers::WithinRel(1.9968, 1e-4));
  }

  SECTION("Verify reactions")
  {
    REQUIRE(cp.n_reactions_ == 3);
    CHECK(cp.MT_[0] == 2);   // elastic
    CHECK(cp.MT_[1] == 50);  // d,d -> n + He3
    CHECK(cp.MT_[2] == 600); // d,d -> p + t

    // Q-values
    CHECK_THAT(cp.Q_value_[0], Catch::Matchers::WithinAbs(0.0, 1e-6));
    CHECK_THAT(cp.Q_value_[1] / 1e6, Catch::Matchers::WithinRel(3.269, 0.01));
    CHECK_THAT(cp.Q_value_[2] / 1e6, Catch::Matchers::WithinRel(4.033, 0.01));

    // Ejectile types
    CHECK(cp.ejectile_[0] == ParticleType::deuteron); // elastic
    CHECK(cp.ejectile_[1] == ParticleType::neutron);  // d,d -> n + He3
    CHECK(cp.ejectile_[2] == ParticleType::proton);   // d,d -> p + t
  }

  SECTION("Verify cross section lookup")
  {
    // Test at 100 keV
    double E = 1e5;

    // Elastic (MT=2) - ENDF-B-VIII.1 value at 100 keV
    double xs_elastic = cp.xs(0, E);
    CHECK_THAT(xs_elastic, Catch::Matchers::WithinRel(0.0287, 0.02));

    // Fusion cross sections
    double xs_n_he3 = cp.xs(1, E);
    double xs_p_t = cp.xs(2, E);

    std::cout << "\nCross sections at 100 keV:" << std::endl;
    std::cout << "  Elastic: " << xs_elastic << " b" << std::endl;
    std::cout << "  n+He3:   " << xs_n_he3 << " b" << std::endl;
    std::cout << "  p+t:     " << xs_p_t << " b" << std::endl;

    CHECK_THAT(xs_n_he3, Catch::Matchers::WithinRel(0.0163, 0.05));
    CHECK_THAT(xs_p_t, Catch::Matchers::WithinRel(0.0154, 0.05));

    // Total cross section
    double xs_total = cp.total_xs(E);
    CHECK_THAT(xs_total, Catch::Matchers::WithinAbs(xs_elastic + xs_n_he3 + xs_p_t, 1e-10));
  }

  SECTION("Verify particle type conversion")
  {
    CHECK(particle_type_from_string("neutron") == ParticleType::neutron);
    CHECK(particle_type_from_string("proton") == ParticleType::proton);
    CHECK(particle_type_from_string("deuteron") == ParticleType::deuteron);
    CHECK(particle_type_from_string("triton") == ParticleType::triton);
    CHECK(particle_type_from_string("helion") == ParticleType::helion);
    CHECK(particle_type_from_string("alpha") == ParticleType::alpha);

    CHECK(particle_type_to_string(ParticleType::neutron) == "neutron");
    CHECK(particle_type_to_string(ParticleType::deuteron) == "deuteron");
    CHECK(particle_type_to_string(ParticleType::alpha) == "alpha");
  }

  // Clean up
  charged_particles_clear();
  CHECK(data::charged_particles.empty());
}
